"""empty message

Revision ID: 6b9dba1d2023
Revises: ccb6c75861ef
Create Date: 2020-04-26 19:02:02.929020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9dba1d2023'
down_revision = 'ccb6c75861ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
